/*
 * This source file was generated by the Gradle 'init' task
 */
package univjavaprogramming;

import java.util.Scanner;

public class App {
    public void print_calc(){

    }

    public static void main(String[] args) {
        int number = 20231975;
        String name = " 박성준";
        System.out.println(number + name);

        int a = 3;
        double b = 10.123;

        System.out.println(String.format("%d + %.3f = %.3f", a, b, a+b));
        System.out.println(String.format("%d - %.3f = %.3f", a, b, a-b));
        System.out.println(String.format("%d * %.3f = %.5f", a, b, a*b));
        System.out.println(String.format("%d / %.3f = %.7f", a, b, a/b));

        //

        System.out.println(String.format("거스름돈 = %d", 50000 - 200 * 1 - 3000 * 2 - 4900 * 5));
        
       

        

        try (Scanner scanner = new Scanner(System.in)) {
            //

            int a0, b0;
            System.out.print("두 정수를 입력하세요>> ");
            a0 = scanner.nextInt();
            b0 = scanner.nextInt();
            
            System.out.println(String.format("%d + %d = %d", a0, b0, a0+b0));
            System.out.println(String.format("%d - %d = %d", a0, b0, a0-b0));
            System.out.println(String.format("%d * %d = %d", a0, b0, a0*b0));
            System.out.println(String.format("%d / %d = %d", a0, b0, a0/b0));
            System.out.println(String.format("%d %% %d = %d", a0, b0, a0%b0));
            //
            System.out.print("원화를 입력하세요(단위 원)>>");

            double won = scanner.nextDouble();
            double wontod = 1310.0;

            System.out.println(String.format("12000원은 $%.2f입니다.", won / wontod));
            
            //
            
            final double pi = 3.141592;
            
            System.out.print("구의 반지름 : ");
            
            double radius = scanner.nextDouble();
            double volume = (4.0 / 3.0) * pi * Math.pow(radius, 3);

            System.out.println(String.format("구의 부피 = %.2f", volume));
        }
    }
}
